on:
  push:
    tags:
      - 'v*'

name: Publish

jobs:
  release:
    name: GitHub Release
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: marvinpinto/action-automatic-releases@latest
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false

  publish:
    name: Crates.io Publish
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
          name: Install Rust Toolchain
        - uses: katyo/publish-crates@v1
          with:
              registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
